from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from .controller import pprreportcontroller as ppr_report,nac_expense_controller as nac_expense
from .controller import budgetbuildercontroller as budget_builder
from .controller import businesscategorycontroller, businesssubcategorycontroller, costdrivercontroller, allocationlevelcontroller, bsccmapingcontroller, allocationfromcontroller,nac_income_controller as nac_income,dss_contoller
from .controller import allocationmetacontroller as allocMeta
from .controller import commonExcelDataMigrationcontroller as EX
from .controller import fascontroller as fas
urlpatterns = [
                  # ppr report
                  # path('ppr_set', ppr_report.pprinsert, name='ppr_set'),
                  # path('ppr_nac_set',ppr_report.ppr_nac_insert,name='ppr_nac_set'),
                  # path('ppr_nac_set_single',ppr_report.ppr_nac_insert_single,name='ppr_nac_set_single'),
                  # path('ppr_report', ppr_report.ppr_report, name='ppr_report'),
                  # path('finyear_search', ppr_report.finyear_search, name='finyear_search'),
                  # path('ppr_supplier', ppr_report.ppr_supplier, name='ppr_supplier'),
                  # path('ppr_suppliergrp', ppr_report.ppr_suppliergrp, name='ppr_suppliergrp'),
                  # path('ppr_mstbusiness_segment', ppr_report.ppr_mstbusiness_segment, name='ppr_mstbusiness_segment'),
                  path('ppr_bs', ppr_report.ppr_businesssegment, name='ppr_bs'),
                  # path('ppr_cc', ppr_report.ppr_costcentre, name='ppr_cc'),
                  # path('ppr_supplier_dropdown', ppr_report.ppr_supplier_dropdown, name='ppr_supplier_dropdown'),
                  # path('ppr_cccbs', ppr_report.ppr_ccbsdetials, name='ppr_cccbs'),
                  # path('new_expense_list', ppr_report.new_expense_list, name='new_expense_list'),
                  # path('new_expensegrp_list', ppr_report.new_expensegrp_list, name='new_expensegrp_list'),
                  # path('new_subcat_list', ppr_report.new_subcat_list, name='new_subcat_list'),
                  # path('new_expensegrptable_set', ppr_report.new_expensegrptable_set, name='new_expensegrptable_set'),
                  # path('ppr_ecf', ppr_report.ppr_ecf, name='ppr_ecf'),
                  # path('ppr_ecf_filelist', ppr_report.ppr_ecf_Filelist, name='ppr_ecf_filelist'),
                  # path('ppr_ecf_filedownload', ppr_report.ppr_ecf_Filedownload, name='ppr_ecf_filedownload'),
                  # path('ppr_cat_list', ppr_report.new_cat_list, name='ppr_cat_list'),
                  # path('ppr_subcat_list', ppr_report.new_subcat_list, name='ppr_subcat_list'),
                  # # budget builder
                  # path('budget_expensegrp_list', budget_builder.budget_expensegrp_list, name='budget_expensegrp_list'),
                  # path('budget_expense_list', budget_builder.budget_expense_list, name='budget_expense_list'),
                  # path('budget_subcat_list', budget_builder.budget_subcat_list, name='budget_subcat_list'),
                  # path('budget_suppliergrp_list', budget_builder.budget_suppliergrp_list,name='budget_suppliergrp_list'),
                  # path('budget_builder_set', budget_builder.budget_builder_set, name='budget_builder_set'),
                  # path('budget_approver_set', budget_builder.budget_approver_set, name='budget_approver_set'),
                  # path('budget_employeebranch', budget_builder.budget_employeebranch, name='budget_employeebranch'),
                  # path('budget_view_status', budget_builder.view_budget_status, name='budget_view_status'),
                  # path('budget_finyear_search', budget_builder.get_budgetbuilder_finyear, name='budget_finyear_search'),
                  # path('budget_remark', budget_builder.get_budget_remark, name='budget_remark'),
                  # path('supplier_list',budget_builder.supplier_list, name='supplier_list'),
                  #
                  # # allocation urls
                  # path('businesscategory', businesscategorycontroller.businesscategory, name='businesscategory'),
                  # path('businesscategory/<businesscategory_id>', businesscategorycontroller.fetch_businesscategory,name='fetch_businesscategory'),
                  # path('businesscategory_search', businesscategorycontroller.businesscategory_search,name='businesscategory_search'),
                  #
                  # path('business_subcategory', businesssubcategorycontroller.business_subcategory,name='business_subcategory'),
                  # path('business_subcategory/<businesscategory_id>',businesssubcategorycontroller.fetch_business_subcategory, name='fetch_business_subcategory'),
                  # path('business_subcategory_search', businesssubcategorycontroller.business_subcategory_search,name='business_subcategory_search'),
                  #
                  # path('costdriver', costdrivercontroller.costdriver, name='costdriver'),
                  # path('costdriver/<costdriver_id>', costdrivercontroller.fetch_costdriver, name='fetch_costdriver'),
                  # path('costdriver_search', costdrivercontroller.costdriver_search, name='costdriver_search'),
                  #
                  # path('allocationlevel', allocationlevelcontroller.allocationlevel, name='allocationlevel'),
                  # path('allocationlevel/<allocationlevel_id>', allocationlevelcontroller.fetch_allocationlevel,name='fetch_allocationlevel'),
                  # path('allocationlevel_search', allocationlevelcontroller.allocationlevel_search,name='allocationlevel_search'),
                  #
                  # path('bsccmaping', bsccmapingcontroller.bsccmaping, name='bsccmaping'),
                  # path('bsccmaping/<bsccmaping_id>', bsccmapingcontroller.fetch_bsccmaping, name='fetch_bsccmaping'),
                  # path('bsccmaping_search', bsccmapingcontroller.bsccmaping_search, name='bsccmaping_search'),
                  #
                  path('allocation', allocationfromcontroller.allocation, name='allocation'),
                  # path('allocationmeta', allocMeta.allocationmeta_create, name='allocationmeta'),
                  # path('allocation_fetch/<id>/', allocMeta.allocation_fetch_individual, name='allocation_fetch'),
                  #
                  # path('remsbased_allocation', allocMeta.remsbased_allocation, name='remsbased_allocation'),
                  # path('allocationtoppr', allocMeta.allocationtoppr, name='allocationtoppr'),
                  # path('tech_allocation', allocMeta.tech_allocation, name='tech_allocation'),
                  # path('inactive_allocation/<allocation_id>', allocMeta.inactive_allocation, name='inactive_allocation'),
                  # path('allocationexcel_report/<allocation_id>', allocMeta.allocationexcel_report, name='allocationexcel_report'),
                  # path('genrate_gl', allocMeta.genrate_gl, name='genrate_gl'),
                  # path('transaction_ratioallocation', allocMeta.transaction_ratioallocation, name='transaction_ratioallocation'),
                  #
                  # path('upload_excel_data', EX.common_excelUpload, name='upload_excel_data'),
                  # #fas
                  # path('fas_incomedata_upload',fas.income_upload,name='fas_incomedata_upload'),
                  # path('fas_level_fetch',fas.level_fetch,name='fas_level_fetch'),
                  # path('fas_expenseGrp_fetch',fas.expenseGrp_fetch,name='fas_expenseGrp_fetch'),
                  # path('fas_expense_fetch',fas.expense_fetch,name='fas_expense_fetch'),
                  # path('fas_category_fetch',fas.category_fetch,name='fas_category_fetch'),
                  # path('fas_subcat_fetch',fas.subcat_fetch,name='fas_subcat_fetch'),
                  # path('fas_hrdata_upload',fas.hr_data_upload,name='fas_hrdata_upload'),
                  # path('fas_level_four',fas.fas_level_four,name='fas_level_four'),
                  # path('new_expensegrp_masterlist', ppr_report.new_expensegrp_masterlist, name='new_expensegrp_masterlist'),
                  # path('new_expense_masterlist', ppr_report.new_expense_masterlist, name='new_expense_masterlist'),
                  # # path('new_matsercategory_fetch',ppr_report.new_matsercategory_fetch,name='new_matsercategory_fetch'),
                  # # path('ppr_nac_set',ppr_report.ppr_nac_insert,name='ppr_nac_set'),
                  # path('budget_new_expensegrp_list', budget_builder.new_budget_expensegrp_list, name='budget_new_expensegrp_list'),
                  # path('budget_new_expense_list', budget_builder.new_budget_expense_list, name='budget_new_expense_list'),
                  # path('budget_cat_list', budget_builder.new_budget_cat_list, name='budget_cat_list'),
                  # path('budget_new_subcat_list', budget_builder.budget_new_subcat_list, name='budget_new_subcat_list'),
                  # path('budget_draft_set', budget_builder.budget_draft_set, name='budget_draft_set'),
                  # path('budget_status_set', budget_builder.budget_status_set, name='budget_status_set'),
                  # path('document_upload', budget_builder.document_upload, name='document_upload'),
                  # path('asset_class_search',nac_income.ppr_assetclass_search,name='asset_class_search'),
                  #
                  # path('fileupload_acti_clients', nac_income.fileupload_acti_clients, name='document_upload'),
                  path('fileupload_cc_income', nac_income.fileupload_cc_income, name='fileupload_cc_income'),
                  # path('income_header_fetch', nac_income.income_header_fetch, name='income_header_fetch'),
                  # path('income_header_date', nac_income.income_header_date, name='income_header_date'),
                  # path('income_header_amount', nac_income.income_header_amount, name='income_header_amount'),
                  # path('income_amount_date', nac_income.income_amount_date, name='income_amount_date'),
                  # path('ppr_client_list',nac_income.ppractiveclients_list,name='ppr_client_list'),
                  # path('ppr_client_date',nac_income.ppractiveclients_date,name='ppr_client_date'),
                  # path('asset_class',nac_income.ppr_assetclass,name='asset_class'),
                  # path('get_masterbuisness',nac_income.get_masterbuisness,name='get_masterbuisness'),
                  # path('ppr_income_filedownload',nac_income.ppr_income_Filedownload,name='ppr_income_filedownload'),
                  path('set_pprsources',nac_income.create_ppr_sources,name='set_pprsources'),
                  path('set_head_groups',nac_income.create_head_groups,name='set_head_groups'),
                  path('set_sub_groups',nac_income.create_sub_groups,name='set_sub_groups'),
                  path('pprsources_list',nac_income.ppr_sources_list,name='pprsources_list'),
                  path('ppr_headgrps_list',nac_income.ppr_head_groups_list,name='ppr_headgrps_list'),
                  path('ppr_subgrps_list',nac_income.ppr_sub_groups_list,name='set_sub_groups'),
                  path('set_gl_subgroup',nac_income.create_GL_subgrp,name='set_gl_subgroup'),
                  path('ppr_gl_subgrp_list',nac_income.ppr_GL_subgrps_list,name='ppr_gl_subgrp_list'),
                  path('ppr_source_dropdown',nac_income.source_list_dropdown,name='ppr_source_dropdown'),
                  path('ppr_headgrps_dropdown',nac_income.headgrp_list_dropdown,name='ppr_headgrps_dropdown'),
                  path('ppr_subgrps_dropdown',nac_income.subgrp_list_dropdown,name='ppr_subgrps_dropdown'),
                  path('ppr_glsubgrps_dropdown',nac_income.gl_subgroup_list_dropdown,name='ppr_glsubgrps_dropdown'),
                  # path('ppr_incomegrp_list', nac_income.ppr_incomegrp_list, name='ppr_incomegrp_list'),
                  # path('ppr_incomehead_list', nac_income.ppr_incomehead_list, name='ppr_incomehead_list'),
                  # path('ppr_incomecat_list', nac_income.ppr_incomecat_list, name='ppr_incomecat_list'),
                  # path('ppr_income_subcat_list', nac_income.ppr_income_subcat_list, name='ppr_income_subcat_list'),
                  # path('ppr_expense_overall_set', nac_expense.ppr_expense_overall_upload, name='ppr_expense_overall_set'),
                  # path('ppr_expensegrp_list', nac_expense.ppr_expensegrp_list, name='ppr_expensegrp_list'),
                  # path('ppr_expensehead_list', nac_expense.ppr_expensehead_list, name='ppr_expensehead_list'),
                  # path('ppr_category_list', nac_expense.ppr_category_list, name='ppr_category_list'),
                  # path('ppr_subcategory_list', nac_expense.ppr_subcategory_list, name='ppr_subcategory_list'),
                  # #vendor
                  # path('supplier_list',budget_builder.supplier_list,name='suplierlist'),
                  path('dss_upload',dss_contoller.dss_upload,name='dss_upload'),
                  path('dssdate_level_list',dss_contoller.ppr_dssdate_level_list,name='dssdate_level_list'),
                  # #New_Allocation
                  # path('new_allocation_list', allocationlevelcontroller.new_allocation_level_list, name='new_allocation_list'),
                  # path('new_allocation_pprinsert', allocationlevelcontroller.new_allocation_pprinsert, name='new_allocation_pprinsert'),
                  # path('level_core_get',allocationlevelcontroller.get_core,name='level_core_get'),
                  # path('business_fetch',allocationlevelcontroller.bussiness_data,name='business_fetch'),
                  # path('bs_fetch',allocationlevelcontroller.bs_data,name='bs_fetch'),
                  # path('cc_fetch',allocationlevelcontroller.cc_data,name='cc_fetch'),
                  # path('allocation', allocationlevelcontroller.ppr_allocation_create, name='businesscategory'),
                  # path('allocation/<id>', allocationlevelcontroller.fetch_allocation,name='allocation_fetch'),
                  # path('allocation_search', allocationlevelcontroller.allcation_search,name='allocation_search'),
                  # path('implementry_status',allocationlevelcontroller.instatus_edit,name='status'),
                  # path('fetch_all',allocationlevelcontroller.fetch_all,name='fetch_all'),
                  # path('total_amount',allocationlevelcontroller.ppr_data,name='total_amount'),
                  # path('modify_allocation',allocationlevelcontroller.modify_allocation,name='modify'),
                  # #New_income
                  # path('new_incomegrp_list', nac_income.new_ppr_incomegrp, name='new_incomegrp_list'),
                  # path('new_incomehead_list', nac_income.new_ppr_incomehead, name='new_incomehead_list'),
                  # path('new_incomecat_list', nac_income.new_ppr_incomecat, name='new_incomecat_list'),
                  # path('new_incomesubcat_list', nac_income.new_income_subcat, name='new_incomesubcat_list'),
                  path('modify_source_status', nac_income.instatus_edit, name='modify_source_status'),
                  path('modify_status_edit', nac_income.status_edit, name='modify_status_edit'),
                  path('modify_subgroup_status', nac_income.modify_status_edit, name='modify_subgroup_status'),
                  path('modify_glsubgroup_status', nac_income.modify_edit, name='modify_glsubgroup_status'),
                  # #dss_report
                  path('dss_profitorloss_list', dss_contoller.dssdate_profitorloss_list, name='dss_profitorloss_list'),
                  path('dss_average_list', dss_contoller.ppr_dssdate_average_list, name='dss_average_list')
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)